spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: user
        password: mypass
        driverClassName: org.postgresql.Driver
    flyway:
        baseline-on-migrate: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL81Dialect
                format_sql: true
        show-sql: true